services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      # Update to use service name instead of external IP
      - REACT_APP_WS_URL=ws://frontend:4000/telemetry

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "14555:14555/udp"
      - "14556:14556/udp"
      - "14557:14557/udp"
      - "14558:14558/udp"
      - "14559:14559/udp"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
